on:
  workflow_call:
    inputs:
      azure-container-registry:
        required: true
        type: string
      release-name:
        required: true
        type: string
      image-version:
        required: true
        type: string
      environment:
        required: true
        type: string 
    secrets:
      container-registry-username:
        required: true
      container-registry-password:
        required: true

jobs:
  build-container-and-push-to-acr:
    name: 'Build container and push to ACR'
    environment: '${{ inputs.environment }}'
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
    # login to Azure Container Registry
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.azure-container-registry }}.azurecr.io
        username: ${{ secrets.container-registry-username }}
        password: ${{ secrets.container-registry-password }}
    # build and push the image
    - run: |
        docker build . --file api.Dockerfile --tag ${{ inputs.azure-container-registry }}.azurecr.io/${{ inputs.release-name }}:${{ inputs.image-version }}
        docker push ${{ inputs.azure-container-registry }}.azurecr.io/${{ inputs.release-name }}:${{ inputs.image-version }}
        docker build . --file cli.Dockerfile --tag ${{ inputs.azure-container-registry }}.azurecr.io/${{ inputs.release-name }}-cli:${{ inputs.image-version }}
        docker push ${{ inputs.azure-container-registry }}.azurecr.io/${{ inputs.release-name }}-cli:${{ inputs.image-version }}