on:
  workflow_call:
    inputs:
      azure-container-registry:
        required: true
        type: string
      release-name:
        required: true
        type: string 
      image-version:
        required: true
        type: string
      environment:
        required: true
        type: string 
    secrets:
      container-registry-username:
        required: true
      container-registry-password:
        required: true

jobs:
  build-helm-chart-and-push-to-acr:
    name: 'Build helm chart and push to ACR'
    environment: '${{ inputs.environment }}'
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v4
    # install helm
    - name: 'Install helm'
      uses: Azure/setup-helm@v4
    # login to Azure Container Registry
    - name: 'Login to acr using helm'
      run: |
        echo $ | helm registry login ${{ inputs.azure-container-registry }}.azurecr.io --username ${{ secrets.container-registry-username }} --password ${{ secrets.container-registry-password }}
    # package and push the chart
    - name: 'Package chart'
      run: cd chart && helm package . --app-version ${{ inputs.image-version }}
    # push the chart
    - name: 'Push chart to acr'
      run: cd chart && helm push ${{ inputs.release-name }}-* oci://${{ inputs.azure-container-registry }}.azurecr.io/helm